image: $CI_REGISTRY/devops/docker/go-build:latest

variables:
  GIT_STRATEGY: none
  REMOTE: remote:artifacts/dockerstart

before_script:
  - mkdir -p ${HOME}/.config/rclone
  - echo "$REMOTE_CONF" > $HOME/.config/rclone/rclone.conf
  - echo $(pwd)
  
build:
  stage: build
  script:
    - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL src/dockerstart
    - go build dockerstart
    - rclone move -uv bin/dockerstart ${REMOTE}/x64/
    - GOARCH=386 go build dockerstart
    - rclone move -uv bin/dockerstart ${REMOTE}/x86/
  tags:
    - docker
