image: $CI_REGISTRY/devops/docker/go-build:latest

variables:
  GIT_STRATEGY: none

stages:
  - pull

.job: &job
  tags:
    - docker

pull:
  <<: *job
  stage: pull
  script:
    - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL /go/src/dockerstart
    - go install dockerstart
