image: $CI_REGISTRY/devops/docker/go-build:latest

stages:
  - pull
  - build
  - clear

variables:
  GIT_STRATEGY: none
  
  NAME: dockerstart
  REMOTE: remote:artifacts/${NAME}
  GOPATH: $CI_PROJECT_DIR

cache:
  paths:
    - ${GOPATH}
  
pull:
  stage: pull
  script:
    - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL src/${NAME}
  tags:
    - docker

build.x64:
  stage: build
  variables:
    GOARCH: amd64
  before_script:
    - mkdir -p ${HOME}/.config/rclone
    - echo "$REMOTE_CONF" >  ${HOME}/.config/rclone/rclone.conf

  script:
    - go build -o ${NAME}.${GOARCH} ${NAME}
    - rclone move -uv ${NAME}.${GOARCH} ${REMOTE}/x64/${NAME}
  tags:
    - docker


build.x86:
  stage: build
  variables:
    GOARCH: amd64
  
  before_script:
    - mkdir -p ${HOME}/.config/rclone
    - echo "$REMOTE_CONF" >  ${HOME}/.config/rclone/rclone.conf

  script:
    - go build -o ${NAME}.${GOARCH} ${NAME}
    - rclone move -uv ${NAME}.${GOARCH} ${REMOTE}/x64/${NAME}
  tags:
    - docker

clear:
  stage: clear
  when: always
  allow_failure: true
  script:
    - rm -rf ${GOPATH/*
