image: $CI_REGISTRY/devops/docker/go-build:latest

variables:
  GIT_STRATEGY: none
  TARGET_BASE: remote:artifacts/dockerstart

before_script:
  - mkdir \
      $HOME
      $HOME/.config/ \
      $HOME/.config/rclone
  - echo "$REMOTE_CONF" > $HOME/.config/rclone/rclone.conf
  
build:
  stage: build
  script:
    - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL /go/src/dockerstart
    - go build dockerstart
    - rclone copy /go/bin/dockerstart $TARGET_BASE/x64/
    - GOARCH=386 go build dockerstart
    - rclone copy bin/dockerstart $TARGET_BASE/x86/
  tags:
    - docker
