image: $CI_REGISTRY/devops/docker/go-build:latest

variables:
  GIT_STRATEGY: none
  
  NAME: dockerstart
  REMOTE: remote:artifacts/${NAME}
  GOPATH: $CI_PROJECT_DIR


stages:
  - pull
  - build

before_script:
  - mkdir -p ${HOME}/.config/rclone
  - echo "$REMOTE_CONF" >  ${HOME}/.config/rclone/rclone.conf
  
pull:
  stage: pull
  script:
    - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL src/${NAME}
  tags:
    - docker

build.x64:
  stage: build
  variables:
    GOARCH: amd64
  script:
    - go build ${NAME}.${GOARCH}
    - rclone move -uv ${NAME}.${GOARCH} ${REMOTE}/x64/${NAME}
  tags:
    - docker


build.x86:
  stage: build
  variables:
    GOARCH: amd64
  script:
    - go build ${NAME}.${GOARCH}
    - rclone move -uv ${NAME}.${GOARCH} ${REMOTE}/x64/${NAME}
  tags:
    - docker