image: $CI_REGISTRY/devops/docker/go-build:latest
stages:
  - pull
  - build
  - clear

variables:
  GIT_STRATEGY: none
  
  NAME: dockerstart
  REMOTE: remote:artifacts/${NAME}
  GOPATH: $CI_PROJECT_DIR
  
pull:
  stage: pull
  script:
    - '[ -d "src/${NAME}"] && rm -rf src/${NAME}'
    - git clone -b $CI_COMMIT_REF_NAME $CI_REPOSITORY_URL src/${NAME}
    - mkdir .config
    - echo "$REMOTE_CONF" >  .config/rclone.conf
  tags:
    - docker
  cache:
    key: "${CI_PIPELINE_ID}"
    paths:
      - src
      - .config

.build: &build
  stage: build
  before_script:
    
  script:
    - go build -o ${NAME}.${GOARCH} ${NAME}
    - rclone moveto -uv ${NAME}.${GOARCH} ${REMOTE}/${ARCH}/${NAME} --config .config/rclone.conf
  tags:
    - docker
  cache:
    key: "${CI_PIPELINE_ID}"
    policy: pull
    paths:
      - src
      - .config
    
build.x64:
  <<: *build
  variables:
    GOARCH: amd64
    ARCH: x64

build.x86:
  <<: *build
  variables:
    GOARCH: "386"
    ARCH: x86
